export const COUNTER_INCREMENT = "COUNTER_INCREMENT"
export const COUNTER_DECREMENT = "COUNTER_DECREMENT"

export const MEDICINE_GET = "MEDICINE_GET"
export const MEDICINE_ADD = "MEDICINE_ADD"
export const MEDICINE_UPDATE = "MEDICINE_UPDATE"
export const MEDICINE_DELETE = "MEDICINE_DELETE"
export const MEDICINE_LOADING = "MEDICINE_LOADING"


export const WATCH_GET = "WATCH_GET"
export const WATCH_ADD = "WATCH_ADD"
export const WATCH_PUT = "WATCH_PUT"
export const WATCH_DELETE = "WATCH_DELETE"
export const WATCH_LOADING = "WATCH_LOADING"
export const WATCH_ERRORE = "WATCH_ERRORE"