export const COUNTER_INCREMENT = "COUNTER_INCREMENT"
export const COUNTER_DECREMENT = "COUNTER_DECREMENT"

export const MEDICINE_GET = "MEDICINE_GET"
export const MEDICINE_ADD = "MEDICINE_ADD"
export const MEDICINE_UPDATE = "MEDICINE_UPDATE"
export const MEDICINE_DELETE = "MEDICINE_DELETE"
export const MEDICINE_LOADING = "MEDICINE_LOADING"


export const WATCH_GET = "WATCH_GET"
export const WATCH_ADD = "WATCH_ADD"
export const WATCH_PUT = "WATCH_PUT"
export const WATCH_DELETE = "WATCH_DELETE"
export const WATCH_LOADING = "WATCH_LOADING"
export const WATCH_ERRORE = "WATCH_ERRORE"

export const MEN_GET_DATA = "MEN_GET_DATA"
export const MEN_POST_DATA = "MEN_POST_DATA"
export const MEN_PUT_DATA = "MEN_PUT_DATA"
export const MEN_DELETE_DATA = "MEN_DELETE_DATA"    
export const MEN_LOADING= "MEN_LOADING"   

export const WOMEN_GET_DATA = "WOMEN_GET_DATA"
export const WOMEN_POST_DATA = "WOMEN_POST_DATA"
export const WOMEN_PUT_DATA = "WOMEN_PUT_DATA"
export const WOMEN_DELETE_DATA = "WOMEN_DELETE_DATA"
export const WOMEN_LOADING= "WOMEN_LOADING"   


export const KID_GET_DATA= "KID_GET_DATA"   
export const KID_POST_DATA = "KID_POST_DATA"
export const KID_PUT_DATA = "KID_PUT_DATA"
export const KID_DELETE_DATA = "KID_DELETE_DATA"
export const KID_LOADING_DATA = "KID_LOADING_DATA"
export const KID_ERRORE_DATA = "KID_ERRORE_DATA"


export const THEME_TOGGLE = "THEME_TOGGLE"


